# Generated by Django 5.0.6 on 2024-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner',
            field=models.BooleanField(blank=True, null=True, verbose_name='владелец'),
        ),
    ]
