# Generated by Django 5.0.6 on 2024-07-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.payment', verbose_name='подписка'),
        ),
    ]
