# Generated by Django 5.0.6 on 2024-07-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_payment',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
