# Generated by Django 5.0.6 on 2024-07-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_is_published_blog_is_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_payment',
            field=models.BooleanField(default=False, verbose_name='Платный контент'),
        ),
    ]
